#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.w3schools.com/html/default.asp permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
