#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/shorts/yY4oVLouk7Q;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
