#!/usr/bin/env bash
#Creating a script that uses if, else if and else statements
m=1
while [ $m -le 10 ]
do
	if [ $m -eq 4 ]
	then
	    echo "bad luck"
	elif [ $m -eq 8 ]
	then
	    echo "good luck"
       	else
	    echo "Holberton School"
	fi
	((m++))
done
